In [9]:
import pandas as pd

df = pd.read_csv('data.csv')

df

,dac_family,hour,dn_count,dn_notvalid_count,dn_ok_count,dn_nxd_count,dn_nxd_notvalid_count,day,hour-2,dac_family-2,...,llr1_nx,llr1_qr_notvalid,llr1_q_notvalid,llr1_nx_notvalid,llr1_fa,llr1_fa_ok,llr1_fa_nx,llr1_macfa,llr1_macfa_ok,llr1_macfa_nx
0,healthy,0,56058,2650,52642,2829,1296,0,0,healthy,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1,modpack,0,56059,2650,52643,2829,1296,0,0,modpack,...,NaN,NaN,NaN,NaN,-8.132352,-16.264704,NaN,-24.397056,-32.529408,NaN
2,necurs,0,60063,2650,54892,4453,1296,0,0,necurs,...,inf,NaN,NaN,NaN,inf,inf,inf,inf,inf,inf
3,virut,0,56059,2650,52643,2829,1296,0,0,virut,...,NaN,NaN,NaN,NaN,-22.253365,-22.253365,NaN,-22.253365,-22.253365,NaN
4,conficker,1,47938,2112,45687,2103,1076,0,1,conficker,...,5.063782e+04,NaN,NaN,NaN,1855.722223,2972.304672,1663.399606,6830.362379,5253.226402,4261.997072
5,healthy,1,47693,2112,45543,2003,1076,0,1,healthy,...,inf,inf,inf,inf,NaN,NaN,inf,NaN,NaN,inf
6,modpack,1,47694,2112,45544,2003,1076,0,1,modpack,...,NaN,NaN,NaN,NaN,-5.421568,-8.132352,NaN,-10.843136,-10.843136,NaN
7,necurs,1,48522,2112,45992,2367,1076,0,1,necurs,...,inf,NaN,NaN,NaN,inf,inf,inf,inf,inf,inf
8,healthy,2,39804,1573,38042,1584,793,0,2,healthy,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
9,modpack,2,39805,1573,38043,1584,793,0,2,modpack,...,NaN,NaN,NaN,NaN,NaN,-2.710784,NaN,-2.710784,-10.843136,NaN
10,necurs,2,43005,1573,39807,2944,793,0,2,necurs,...,inf,NaN,NaN,NaN,inf,inf,inf,inf,inf,inf

In [14]:
df = pd.read_csv('data.csv')

for col in ["dn_count","dn_notvalid_count","dn_ok_count","dn_nxd_count","dn_nxd_notvalid_count"]:
    df[col] = df.groupby('hour')[col].transform(lambda x: x - x.mean())
    print(df.groupby('hour')[col].mean())

df

hour
0    0.000000e+00
1    0.000000e+00
2   -2.425319e-12
Name: dn_count, dtype: float64
hour
0    0.0
1    0.0
2    0.0
Name: dn_notvalid_count, dtype: float64
hour
0    0.000000e+00
1    0.000000e+00
2    2.425319e-12
Name: dn_ok_count, dtype: float64
hour
0    0.000000e+00
1    0.000000e+00
2    7.579123e-14
Name: dn_nxd_count, dtype: float64
hour
0    0.0
1    0.0
2    0.0
Name: dn_nxd_notvalid_count, dtype: float64

,dac_family,hour,dn_count,dn_notvalid_count,dn_ok_count,dn_nxd_count,dn_nxd_notvalid_count,day,hour-2,dac_family-2,...,llr1_nx,llr1_qr_notvalid,llr1_q_notvalid,llr1_nx_notvalid,llr1_fa,llr1_fa_ok,llr1_fa_nx,llr1_macfa,llr1_macfa_ok,llr1_macfa_nx
0,healthy,0,-1001.750000,0.0,-563.000000,-406.000000,0.0,0,0,healthy,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1,modpack,0,-1000.750000,0.0,-562.000000,-406.000000,0.0,0,0,modpack,...,NaN,NaN,NaN,NaN,-8.132352,-16.264704,NaN,-24.397056,-32.529408,NaN
2,necurs,0,3003.250000,0.0,1687.000000,1218.000000,0.0,0,0,necurs,...,inf,NaN,NaN,NaN,inf,inf,inf,inf,inf,inf
3,virut,0,-1000.750000,0.0,-562.000000,-406.000000,0.0,0,0,virut,...,NaN,NaN,NaN,NaN,-22.253365,-22.253365,NaN,-22.253365,-22.253365,NaN
4,conficker,1,-23.750000,0.0,-4.500000,-16.000000,0.0,0,1,conficker,...,5.063782e+04,NaN,NaN,NaN,1855.722223,2972.304672,1663.399606,6830.362379,5253.226402,4261.997072
5,healthy,1,-268.750000,0.0,-148.500000,-116.000000,0.0,0,1,healthy,...,inf,inf,inf,inf,NaN,NaN,inf,NaN,NaN,inf
6,modpack,1,-267.750000,0.0,-147.500000,-116.000000,0.0,0,1,modpack,...,NaN,NaN,NaN,NaN,-5.421568,-8.132352,NaN,-10.843136,-10.843136,NaN
7,necurs,1,560.250000,0.0,300.500000,248.000000,0.0,0,1,necurs,...,inf,NaN,NaN,NaN,inf,inf,inf,inf,inf,inf
8,healthy,2,-1067.333333,0.0,-588.666667,-453.333333,0.0,0,2,healthy,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
9,modpack,2,-1066.333333,0.0,-587.666667,-453.333333,0.0,0,2,modpack,...,NaN,NaN,NaN,NaN,NaN,-2.710784,NaN,-2.710784,-10.843136,NaN
10,necurs,2,2133.666667,0.0,1176.333333,906.666667,0.0,0,2,necurs,...,inf,NaN,NaN,NaN,inf,inf,inf,inf,inf,inf